name: Testes Automatizados

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Subir containers da aplicação
        run: docker compose up -d

      - name: Esperar o container iniciar
        run: sleep 5

      - name: Aguardar o servidor responder na porta 3311
        run: |
          for i in {1..30}; do
            echo "Tentando conectar em http://localhost:3311 (tentativa $i)..."
            if curl --silent --fail http://localhost:3311 > /dev/null; then
              echo "Servidor disponível!"
              break
            fi
            sleep 1
          done

      - name: Instalar dependências dentro do container
        run: docker compose exec -T app npm install

      - name: Executar testes unitários dentro do container
        run: docker compose exec -T app npm run test:unit

      - name: Executar testes de aceitação dentro do container
        run: docker compose exec -T app npx cucumber-js

      - name: Encerrar containers
        if: always()
        run: docker compose down
